### ISSUE TITLE
看着非常美，可惜缺乏使用教程

### ISSUE THREAD

**Issue by bubifengyun** [liantze/pgfornament-han#3]
特别喜欢图片中的回文线，想把他加入我写的文章中，https://github.com/bubifengyun/deepin-bible 求入门指导，谢谢。

**Comment by bubifengyun** [comment]
抱歉，我先下载，折腾一下，谢谢啦。有问题，再来提问。

**Comment by liantze** [comment]
Out of scope了，不会在这个项目里边加入 mark down 或 bookdown 了，一个项目专注一个目的就好，尤其是这个项目是要同步到 CTAN 的。但是欢迎自行在这个宏包上各种多种疯狂尝试，可以参考一下文章：
- http://www.latexstudio.net/archives/6774
- http://www.latexstudio.net/archives/7266
- https://www.overleaf.com/blog/441-how-to-write-in-markdown-on-overleaf
- https://www.overleaf.com/blog/501-markdown-into-latex-with-style
