### ISSUE TITLE
添加第二个\section时会报错

### ISSUE THREAD

**Issue by luoyt14** [liantze/pgfornament-han#5]
使用多于一个section时，后面的section会报错：
`Command \cloud@secname@height already defined. Or name \end... illegal, see p.192 of the manual`

**Comment by luoyt14** [comment]
修改beamerthemeHeavenlyClouds.sty文件的第143行即可解决

**Comment by liantze** [comment]
谢谢，已修正 #50590e9

**Comment by muzimuzhi** [comment]
https://github.com/liantze/pgfornament-han/commit/50590e984a527b42975ba89ab017ac1ebb028cdb (just to provide a link to the fix)
